version = 1
SPDX-PackageName = "xk6-grpcresolver"
SPDX-PackageSupplier = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/xk6-grpcresolver"

[[annotations]]
path = [
    ".gitignore",
    ".github/**",
    "*.md",
    "repolinter.json",
    "REUSE.toml",
    "Makefile",
    "docker/**",
    "examples/**",
    "go.mod",
    "go.sum",
]
SPDX-FileCopyrightText = "2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
